name: food_truck
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.1+1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.0
  json_annotation: ^4.9.0
  logger: ^2.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen/Sen-VariableFont_wght.ttf
