name: CI/CD Pipeline

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Read CURRENT_PROFILE from .env file
        id: read_env
        run: |
          echo "CURRENT_PROFILE=$(grep '^CURRENT_PROFILE=' .env | cut -d '=' -f 2)" >> $GITHUB_ENV

      - name: Build with Maven
        if: env.CURRENT_PROFILE == 'prod'
        run: mvn clean package -DskipTests

      - name: Create Firebase Config File
        if: env.CURRENT_PROFILE == 'prod'
        run: echo ${{ secrets.FIREBASE_CONFIG_BASE64 }} | base64 -d > src/main/resources/food-truck-f524e-firebase-adminsdk-2szft-579d5d1f9c.json

      - name: Log in to Docker Hub
        if: env.CURRENT_PROFILE == 'prod'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        if: env.CURRENT_PROFILE == 'prod'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/food-truck:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/food-truck:latest .

      - name: Push Docker image (by commit SHA)
        if: env.CURRENT_PROFILE == 'prod'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/food-truck:${{ github.sha }}

      - name: Push Docker image (latest tag)
        if: env.CURRENT_PROFILE == 'prod'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/food-truck:latest

      - name: Logout from Docker Hub
        if: env.CURRENT_PROFILE == 'prod'
        run: docker logout
